apiVersion: v1
kind: Service
metadata:
  name: did-website-node
  namespace: ${k8s_namespace}
  labels:
    app: did-website-node
spec:
  selector:
    app: did-website-node
  ports:
  - port: 3000
    protocol: TCP
  type: ClusterIP
