apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ${k8s_namespace}
data:
  nginx.conf: |-
    worker_processes 1;

    events { worker_connections 1024; }
  
    http {

        sendfile on;

        gzip on;
        gzip_types      text/plain application/xml application/javascript text/javascript text/css image/svg+xml;
        gzip_proxied    no-cache no-store private expired auth;
        gzip_min_length 1000;

        map $http_x_forwarded_proto $thescheme {
             default $scheme;
             https https;
        }

        server {
            listen 8080;

            # don't expose nginx version
            server_tokens off;

            # set client body size to 32M #
            client_max_body_size 32M;

            access_log /var/log/nginx/did_access.log;
            error_log /var/log/nginx/did_error.log;

            location / {
                resolver 127.0.0.1:53 ipv6=off;
                set $backend "http://did-website-node:3000";
                proxy_pass         $backend;
                proxy_redirect     http://did-website-node/ /;
                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $server_name;
                proxy_set_header   X-Forwarded-Server $host;
                proxy_set_header   X-Forwarded-Proto $thescheme;


            }

        }

    }
