apiVersion: apps/v1
kind: Deployment
metadata:
  name: did-website-nginx
  namespace: ${k8s_namespace}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: did-website-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: did-website-nginx
    spec:
      containers:
      - image: nginx
        name: webserver
        imagePullPolicy: Always
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-logs
            mountPath: /var/log/nginx
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: Host
              value: localhost
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 6
      - name: dnsmasq
        image: "janeczku/go-dnsmasq:release-1.0.5"
        args:
        - --listen
        - "127.0.0.1:53"
        - --default-resolver
        - --append-search-domains
        - --hostsfile=/etc/hosts
        - --verbose
      - image: designisdead/fluent
        name: fluent
        env:
          - name: FLUENTD_ARGS
            value: -c /etc/td-agent/td-agent.conf
          - name: LOG_GROUP_NAME
            value: ${k8s_namespace}
          - name: LOG_STREAM_NAME
            value: "did-nginx"
          - name: AWS_REGION
            value: "eu-central-1"
        volumeMounts:
          - name: nginx-logs
            mountPath: /var/log/nginx
          - name: fluent-config-volume
            mountPath: /etc/td-agent
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhubcred
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: nginx-logs
          emptyDir: {}
        - name: fluent-config-volume
          configMap:
            name: nginx-fluentd-config
